services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      TZ: Asia/Tokyo
    command: start-dev
  db:
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Tokyo
volumes:
  keycloak-db: